language: android

java: oraclejdk8 # We need this if your sdk version is 24

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-30

    # Additional components
    #- extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-30"


script:
  - ./gradlew build

notifications:
  slack: soundrecorderteam:Nut7a5FL3Y7KkjpaJU1yhgMi
