language: android

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-21
    # Additional components
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

#  Save time not downloading dependencies ad every build
cache:
  directories:
    ~/.gradle/caches/
    ~/.gradle/wrapper/

addons:
  apt:
    packages:
      - lynx

before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-21"

stages:
  - compile
  - static_analysis

jobs:
  include:
    - stage: compile
      name: "Compile"
      script: ./gradlew build
    - stage: static_analysis
      name: "Checkstyle analysis"
      script: ./gradlew checkstyle
      after_success: lynx -dump file:///home/travis/build/assuntaDC/SoundRecorder/app/build/reports/checkstyle/checkstyle.html
    - script: ./gradlew pmd
      name: "PMD analysis"
      after_success: lynx -dump file:///home/travis/build/assuntaDC/SoundRecorder/app/build/reports/pmd/pmd.html
      artifacts:
        name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        expire_in: 4 days
        paths:
          - app/build/reports/



notifications:
  slack: soundrecorderteam:Nut7a5FL3Y7KkjpaJU1yhgMi